trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install and Build'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/dist'
    artifactName: 'node-app-artifact'
  displayName: 'Publish Artifact'
  
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifactName: 'node-app-artifact'
    targetPath: '$(System.DefaultWorkingDirectory)/dist'
  displayName: 'Download Artifact'
  
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'subscription name'
    appName: 'app name'
    package: '$(System.DefaultWorkingDirectory)/dist'
    appType: 'webApp'
  displayName: 'Deploy to Azure App Service'
